// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Poppins } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/app/context/useUser";
import { Toaster } from "react-hot-toast"; // 👈 IMPORTANTE

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manropeFont = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const poppinsFont = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Incell System: Adac Church",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manropeFont.variable} ${poppinsFont.variable} antialiased`}
      >
        <AuthProvider>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 6000,
              style: {
                background: "#333",
                color: "#fff",
                borderRadius: "10px",
                padding: "10px 15px",
              },
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
